### ISSUE TITLE
NETWORK doesn't seem to work as I expect

### ISSUE THREAD

**Issue by JeffreyFalgout** [thbrown/softball-sim#2]
I recorded a game in https://github.com/thbrown/softball-scorer, and now I want to generate a lineup for next week's game.

I don't see anything obvious in softball.app to do that, so I tried running softball-sim.jar locally with NETWORK. It seems to be trying to connect to localhost to get the data, which makes me think I'm holding it wrong.

I don't really want to munge the softball.app export to the softball-sim FILESYSTEM input format, either, but I suppose that could be a workaround.

**Comment by thbrown** [comment]
This will be making its way into the app in production soon. In the mean time, try cloning the scorer (https://github.com/thbrown/softball-scorer) and running the app server on localhost (this requires minimal setup [just node and npm] instructions are the top part of the README, skip all the optional features).

You should be able to export your data from prod softball.app in the main menu, then import that file into the app server running on localhost after creating an account. From there you can run simulations by creating a new 'optimization' in the main main menu inside the localhost app.

It will automatically download the simulation jar from this repo and use it to generate the (hopefully) optimal lineup.

**Comment by JeffreyFalgout** [comment]
That works too. Thanks!
